# Generated by Django 3.2.5 on 2021-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0005_alter_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='species',
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
