# Generated by Django 3.2.5 on 2021-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0007_auto_20210726_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
    ]
