# Generated by Django 3.2.5 on 2021-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0009_rename_eye_color_person_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
